on:
  workflow_call:
    secrets:
      channelId:
        required: true
      slackToken:
        required: true

jobs:
  notify_slack_push:
    name: Notify Slack commit on pushes
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack commit
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slackToken }}
          CHANNEL_ID: ${{ secrets.channelId }}
          REPO: ${{ github.event.repository.name }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          PUSHER: ${{ github.event.pusher.name }}
          COMPARE_URL: ${{ github.event.compare }}
        run: |
          set -euo pipefail

          payload="$(jq -n \
            --arg channel "$CHANNEL_ID" \
            --arg repo "$REPO" \
            --arg msg "$COMMIT_MSG" \
            --arg pusher "$PUSHER" \
            --arg url "$COMPARE_URL" \
            '{
              channel: $channel,
              blocks: [
                {
                  type: "section",
                  text: {
                    type: "mrkdwn",
                    text: ("*[" + $repo + "]:* " + $msg + "\n *Av:* " + $pusher + "\n <" + $url + "|Kolla ändringar>")
                  }
                }
              ]
            }')"

          response="$(curl -sS -X POST \
            -H "Content-Type: application/json; charset=utf-8" \
            -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" \
            --data "${payload}" \
            https://slack.com/api/chat.postMessage)"

          echo "${response}" | grep -q '"ok":true' || {
            echo "Slack API error:"
            echo "${response}"
            exit 1
          }
        if: success()