on:
  workflow_call:
    secrets:
      channelId:
        required: true
      slackToken:
        required: true

jobs:
  notify_slack_push:
    name: Notify Slack PR on pushes
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack PR
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slackToken }}
          CHANNEL_ID: ${{ secrets.channelId }}
          REPO: ${{ github.event.repository.name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          set -euo pipefail

          payload="$(jq -n \
            --arg channel "$CHANNEL_ID" \
            --arg repo "$REPO" \
            --arg title "$PR_TITLE" \
            --arg author "$PR_AUTHOR" \
            --arg url "$PR_URL" \
            --arg number "$PR_NUMBER" \
            '{
              channel: $channel,
              blocks: [
                {
                  type: "section",
                  text: {
                    type: "mrkdwn",
                    text: ("*[" + $repo + "]*: " + $title + "\n Av: " + $author + "\n <" + $url + "|PR " + $number + ">")
                  }
                }
              ]
            }')"

          response="$(curl -sS -X POST \
            -H "Content-Type: application/json; charset=utf-8" \
            -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" \
            --data "${payload}" \
            https://slack.com/api/chat.postMessage)"

          echo "${response}" | grep -q '"ok":true' || {
            echo "Slack API error:"
            echo "${response}"
            exit 1
          }
        if: success()