on:
  workflow_call:
    inputs:
      channelId:
        required: true
        type: string
      repository:
        required: true
        type: string
      message:
        required: true
        type: string
      name:
        required: true
        type: string
      SLACK_GITHUB_ACTIONS_TOKEN:
        required: true
        type: string

jobs:
  notify_slack_push:
    name: Notify Slack on pushes
    runs-on: ubuntu-latest
    steps:
      - uses: abinoda/slack-action@master
        env:
          SLACK_GITHUB_ACTIONS_TOKEN: ${{ secrets.SLACK_GITHUB_ACTIONS_TOKEN }}
        with:
        # message to send to slack
          args: '{\"channel\":\"${{ inputs.channelId }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Projekt:* ${{ inputs.repository }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Av:* ${{ inputs.name }}\n*Ändringar:* ${{ inputs.message }}\"}}]}' 
        if: success()